version: '3'

services:
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    ports: [5432]
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data: